{% set version = "2.2.5" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz 
  md5: 02dae671aa5ad955fdcbcd3fee313fb7
  patches:
    - no-console.patch

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  # [win]

test:
  requires:
    - python 3.6  # [not (win and vc<14)]
    - python 2.7  # [win and vc<14]
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libmuparser${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\muparser.dll']"  # [win]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
