{% set version = "2.2.5" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: 0666ef55da72c3e356ca85b6a0084d56b05dd740c3c21d26d372085aa2c6e708
  patches:
    - no-console.patch

build:
  number: 5

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - conda inspect linkages -p ${PREFIX} muparser  # [not win]
    - conda inspect objects -p ${PREFIX} muparser  # [osx]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
