{% set version = "2.3.2" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: b35fc84e3667d432e3414c8667d5764dfa450ed24a99eeef7ee3f6647d44f301

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('muparser', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp  # [osx]
  run:
    - llvm-openmp  # [osx]
test:
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - test -f ${PREFIX}/lib/libmuparser${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\muparser.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\muparser.dll exit 1  # [win]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
