{% set version = "2.2.5" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz 
  md5: 02dae671aa5ad955fdcbcd3fee313fb7
  patches:
    - no-console.patch

build:
  number: 2
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py36]

requirements:
  build:
    - toolchain
    - cmake  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libmuparser${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\muparser.dll']"  # [win]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
