{% set version = "2.2.6.1" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: d2562853d972b6ddb07af47ce8a1cdeeb8bb3fa9e8da308746de391db67897b3
  patches:
    - no-console.patch

build:
  number: 1000

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - conda inspect linkages -p ${PREFIX} muparser  # [not win]
    - conda inspect objects -p ${PREFIX} muparser  # [osx]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
