{% set version = "2.2.6.1" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: d2562853d972b6ddb07af47ce8a1cdeeb8bb3fa9e8da308746de391db67897b3
  patches:
    - no-console.patch

build:
  number: 1
  # Requires c++11 unavailable on vc9
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('muparser', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - test -f ${PREFIX}/lib/libmuparser${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\muparser.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\muparser.dll exit 1  # [win]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
