{% set version = "2.3.5" %}

package:
  name: muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: 20b43cc68c655665db83711906f01b20c51909368973116dfc8d7b3c4ddb5dd4

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('muparser', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - llvm-openmp  # [osx]
  run:
    - llvm-openmp  # [osx]
test:
  requires:
    - cmake  # [target_platform == "win-arm64"]
    - {{ compiler('cxx') }}  # [target_platform == "win-arm64"]
  files:
    - CMakeLists.txt  # [target_platform == "win-arm64"]
    - test.cpp  # [target_platform == "win-arm64"]
  commands:
    - test -f ${PREFIX}/include/muParser.h  # [unix]
    - test -f ${PREFIX}/lib/libmuparser${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\muParser.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\muparser.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\muparser.dll exit 1  # [win]
    - cmake -S . -B test-build -G "NMake Makefiles"  # [target_platform == "win-arm64"]
    - if errorlevel 1 exit 1  # [target_platform == "win-arm64"]
    - cmake --build test-build --config Release  # [target_platform == "win-arm64"]
    - if errorlevel 1 exit 1  # [target_platform == "win-arm64"]
    - test-build\muparser_consumer.exe  # [target_platform == "win-arm64"]
    - if errorlevel 1 exit 1  # [target_platform == "win-arm64"]
    - dumpbin /headers test-build\muparser_consumer.exe | findstr /I /C:"AA64 machine (ARM64)"  # [target_platform == "win-arm64"]
    - if errorlevel 1 exit 1  # [target_platform == "win-arm64"]
    - dumpbin /headers "%LIBRARY_BIN%\\muparser.dll" | findstr /I /C:"AA64 machine (ARM64)"  # [target_platform == "win-arm64"]
    - if errorlevel 1 exit 1  # [target_platform == "win-arm64"]

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: LICENSE
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
