appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fmnTC5vLauPf0Yq7TmkQxVXMIXVu+dQR4RAZIaHNQNeRV1k5R6TRvSHPCRcCgC/l+qqkIkoXIImwZLQObb2ykrpx5lRaDg5Au5b1Q3fGEDuQbReFi7i5ie2Pn5+vuhasYz6a13KadIfZYQX8c0Fljz98RdBPZcmVGfcjyeZKvCfzf/9WNR4XFnjUhPcuYNEIWhjLWQezxt6AaVnZy1vQiPU8Fve0bBAzBkuCeNxSpdXyGd5qXfM0V2MmiQhFMgNjN/HBERjgtLsLxU0mec0vlSZZ/nnVACrXDZdZpwz6e/3bhappYmkzjXmYDep/jvKg1NKtUbbSammNMTczyo0O1u6g1wqS/oQzOvsGMdtBjyBd0WH/DosEfeZaBLaFoul4+3nZ18tOsNdEHz7U/zXlztpS6fOSKRxrOJvSu63Kngj4U8N7kGKUSIUxBU4wz969iUsFd/eeCxMu/fI9LYXPEStGnm+8TVBI2LG9F0LQMvwWMW0dNXDRIwvxT631X/Crum8i8Tvq88MBsDjOoShuQMt0hyZNLdtB0YLERCyrYZcyrNK3iFPjceGnwaLkummTyZTZO3Rx70AS9TAYKaIEhYoRfH6ZHJj8Tf2RToGdzGxTB6Nq+nX76mljhihf+4X1MUw2yBePh76aJxdFUByL5Gga3/vQS4RZETLpu4CRgME=}
provider:
  win: azure
conda_forge_output_validation: true
